from asamblea.models import Militante, Puesto
puesto = Puesto.objects.get(id=4)
usuario = Militante.objects.create_user(username='10000',first_name='Monica',last_name='Monica', email='community@partidoverde.org.co', password='10000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='20000',first_name='Natali',last_name='Natali', email='diseno@partidoverde.org.co', password='20000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='30000',first_name='Carlos',last_name='Carlos', email='audiovisuales@alianzaverde.org.co', password='30000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='40000',first_name='Andres Felipe Gil Lozano ',last_name='Andres Felipe Gil Lozano ', email='realizador@partidoverde.org.co', password='40000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='50000',first_name='Daniel',last_name='Daniel', email='desarollotecnologico@partidoverde.org.co', password='50000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='60000',first_name='Diego',last_name='Diego', email='dzambrano@partidoverde.org.co', password='60000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='70000',first_name='john',last_name='john', email='sistemas@partidoverde.org.co', password='70000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='80000',first_name='Wendi',last_name='Wendi', email='asosoriajuridica1@partidoverde.org.co', password='80000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='90000',first_name='Alejandra',last_name='Alejandra', email='cuentas5@partidoverde.org.co', password='90000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='100000',first_name='Erika',last_name='Erika', email='contabilidad@partidoverde.org.co', password='100000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='110000',first_name='Lina',last_name='Lina', email='pagos@partidoverde.org.co', password='110000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='120000',first_name='Jurani',last_name='Jurani', email='asistentecontable@partidoverde.org.co', password='120000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='130000',first_name='Angela',last_name='Angela', email='auditoria-angela@partidoverde.org.co', password='130000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='140000',first_name='Carmen',last_name='Carmen', email='auditoria-carmen@partidoverde.org.co', password='140000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='150000',first_name='Wilches',last_name='Wilches', email='cuentas6@partidoverde.org.co', password='150000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='160000',first_name='Valentina',last_name='Valentina', email='cuentas13@partidoverde.org.co', password='160000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='170000',first_name='GABRIELA JIMENEZ AGUIAR',last_name='GABRIELA JIMENEZ AGUIAR', email='cuentas25@partidoverde.org.co', password='170000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='180000',first_name='Vanesa',last_name='Vanesa', email='cuentas23@partidoverde.org.co', password='180000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='190000',first_name='Dalia',last_name='Dalia', email='recepcion@partidoverde.org.co', password='190000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='200000',first_name='Catalina castiblanco',last_name='Catalina castiblanco', email='asesoracpv@partidoverde.org.co', password='200000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='210000',first_name='Laura vasquez',last_name='Laura vasquez', email='escueladegobierno@partidoverde.org.co', password='210000', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='karol',first_name='karol',last_name='Rojas', email='regiones@partidoverde.org.co', password='karol', is_active= False, location= puesto )
usuario = Militante.objects.create_user(username='230000',first_name='Lina quevedo',last_name='Lina quevedo', email='centropensammiento@partidoverde.org.co', password='230000', is_active= False, location= puesto )
exit()