# Generated by Django 5.2.1 on 2025-06-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='militante',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='militante',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='se envió correo'),
        ),
        migrations.AddField(
            model_name='militante',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asamblea.lista', verbose_name='Lista'),
        ),
    ]
