# Generated by Django 5.2.3 on 2025-06-13 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='num_curul',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (13, '8'), (14, '8'), (17, '17')], default=0, verbose_name='¿N° Curules?'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, verbose_name='F. creación'),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='fm',
            field=models.DateTimeField(auto_now=True, verbose_name='F. modificación'),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Visualizar'),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plancha_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creación'),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario creación'),
        ),
    ]
