# Generated by Django 5.2.1 on 2025-05-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militante',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]
