# Generated by Django 5.2.1 on 2025-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0002_militante_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='militante',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
