# Generated by Django 5.2.1 on 2025-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0002_lista_militante_position_alter_militante_send_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailenviado',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='militante',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña'),
        ),
    ]
