# Generated by Django 5.2.1 on 2025-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0003_emailenviado_fc_alter_militante_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='militante',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género'),
        ),
    ]
