# Generated by Django 5.2.3 on 2025-06-14 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0003_alter_puesto_num_curul'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='F. votación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puesto',
            name='num_curul',
            field=models.IntegerField(choices=[(8, '8'), (14, '14'), (17, '17')], default=8, verbose_name='¿N° Curules?'),
        ),
    ]
