# Generated by Django 5.2.1 on 2025-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0003_alter_militante_options_alter_militante_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militante',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='militante',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
