# Generated by Django 5.2.1 on 2025-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0004_militante_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('indicador', models.IntegerField(default=0)),
                ('idpuesto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cod_puesto', models.CharField(max_length=30)),
                ('puesto_name', models.CharField(max_length=100)),
                ('no_mesas', models.IntegerField()),
                ('cod_zona', models.CharField(max_length=30)),
                ('cod_comuna', models.CharField(max_length=30)),
                ('cod_mun', models.CharField(max_length=30)),
                ('mun_name', models.CharField(max_length=30)),
                ('comuna_name', models.CharField(max_length=30)),
                ('cod_dpto', models.CharField(max_length=30)),
                ('dpto_name', models.CharField(max_length=30)),
                ('curules_asamblea', models.IntegerField(default=0)),
                ('curules_concejo', models.IntegerField(default=0)),
                ('curules_jal', models.IntegerField(default=0)),
                ('potencial_m', models.IntegerField()),
                ('potencial_h', models.IntegerField()),
            ],
        ),
    ]
