# Generated by Django 5.2.1 on 2025-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0004_alter_militante_email_alter_militante_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militante',
            options={},
        ),
        migrations.AddConstraint(
            model_name='militante',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
