# Generated by Django 5.2.1 on 2025-05-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0004_remove_militante_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militante',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
