# Generated by Django 5.2.3 on 2025-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0004_puesto_fecha_alter_puesto_num_curul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='F. votación'),
        ),
    ]
