# Generated by Django 5.2.1 on 2025-05-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0005_alter_militante_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
