# Generated by Django 5.2.1 on 2025-06-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0005_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AddField(
            model_name='militante',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asamblea.puesto', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='plancha',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asamblea.puesto', verbose_name='Ubicación'),
        ),
    ]
