# Generated by Django 5.2.3 on 2025-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0005_alter_puesto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='F. votación'),
        ),
    ]
