# Generated by Django 5.2.3 on 2025-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0006_alter_puesto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='comuna_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Localidad'),
        ),
    ]
