# Generated by Django 5.2.1 on 2025-05-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0006_plancha_candidato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='planca',
            new_name='plancha',
        ),
        migrations.RemoveField(
            model_name='plancha',
            name='email',
        ),
    ]
