# Generated by Django 5.2.1 on 2025-05-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0007_rename_planca_candidato_plancha_remove_plancha_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='plancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asamblea.plancha'),
        ),
    ]
