# Generated by Django 5.2.3 on 2025-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0007_alter_puesto_comuna_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='fecha_fin',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha cierra'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
