# Generated by Django 5.2.1 on 2025-05-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0008_alter_candidato_plancha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['name'], 'verbose_name': 'candidato', 'verbose_name_plural': 'candidatos'},
        ),
        migrations.AlterModelOptions(
            name='plancha',
            options={'ordering': ['name'], 'verbose_name': 'Plancha', 'verbose_name_plural': 'Planchas'},
        ),
        migrations.AddField(
            model_name='plancha',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
