# Generated by Django 5.2.3 on 2025-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0008_puesto_fecha_fin_puesto_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='fecha_fin',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha cierre'),
        ),
    ]
