# Generated by Django 5.2.1 on 2025-05-30 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0009_alter_candidato_options_alter_plancha_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militante',
            name='plancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asamblea.plancha'),
        ),
        migrations.AlterField(
            model_name='militante',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='plancha',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plancha_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
