# Generated by Django 5.2.1 on 2025-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0010_militante_plancha_alter_militante_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna1', models.CharField(max_length=255)),
                ('columna2', models.IntegerField()),
                ('columna3', models.DateField()),
            ],
        ),
    ]
