# Generated by Django 5.2.1 on 2025-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0011_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='columna3',
            field=models.CharField(),
        ),
    ]
