# Generated by Django 5.2.1 on 2025-06-01 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0012_alter_registro_columna3'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancha',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancha',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asamblea.plancha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
