# Generated by Django 5.2.1 on 2025-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0013_plancha_fecha_fin_plancha_fecha_inicio_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancha',
            name='imagen',
            field=models.ImageField(upload_to='opciones_voto/'),
        ),
    ]
