# Generated by Django 5.2.1 on 2025-06-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0014_alter_plancha_imagen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('user', 'opcion')},
        ),
    ]
